[project]
name = "nebula"
version = "0.2.0"
description = "Nebula is a lightweight Python backend framework with middleware and routing, built on top of the standard http.server module. It allows you to create web applications quickly with simple, decorator-based routing."

#[project.dependencies]

[tool.setuptools.packages.find]
where = ["."]
include = ["nebula*"]

[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"